### ISSUE TITLE
Bug: Some profiles can't view the edit/delete trip button

### ISSUE THREAD

**Issue by aboonyanit** [cs210/Daimler-API-1#161]

**Comment by aboonyanit** [comment]
I think it's a UI issue - not sure if the girl had an android cause she said she had issues viewing the map as well

**Comment by alexanderjhurtado** [comment]
Seemed like an issue of hardcoding a width greater than the user's phone's width. Fixed by setting `width: Dimensions.get("window").width * 0.9`
